server:
  port: 8081

spring:
  application:
    name: keycloak-identity-and-access
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/shanrealm2
          jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: shan-rest-api-2
      principle-attribute: preferred_username